# Generated by Django 5.0.7 on 2024-07-22 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('model', models.CharField(max_length=50, verbose_name='Product model')),
                ('release_date', models.DateField(verbose_name='Product release date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Network name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('house_number', models.CharField(max_length=10, verbose_name='House number')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Debt for supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Hierarchy Level')),
                ('type', models.CharField(choices=[('F', 'Factory'), ('R', 'Retail Network'), ('I', 'Individual Entrepreneur')], default='F', max_length=1, verbose_name='Network Type')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplied_by', to='network.network', verbose_name='Supplier')),
                ('products', models.ManyToManyField(blank=True, related_name='networks', to='network.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'ordering': ['level', 'name'],
            },
        ),
    ]
